### ISSUE TITLE
File invalid or does not exist, faild to load

### ISSUE THREAD

**Issue by canhkieu** [linuxdeepin/deepin-music#21]
I can not play any mp3 file after update. 

- I tried to remove and reinstall but not work.
- I tried to chmod music folder -R 777 bot still not work.

![deepinscreenshot20170326100442](https://cloud.githubusercontent.com/assets/136077/24328139/e3a98cb2-120b-11e7-928f-0631a92c00f8.png)

**Comment by zhtengw** [comment]
You need the gstreamer plugins for mpg123, the package name depends on what distribution you are using.

**Comment by dpluy** [comment]
I solved this problem in Archlinux. You can do this: sudo pacman -S gst-libav gst-plugins-good.
Good luck!

**Comment by dpluy** [comment]
I solved this problem in Archlinux. You can do this: 
`sudo pacman -S gst-libav gst-plugins-good`.
Good luck!

**Comment by adierebel** [comment]
try installing this plugin, work well for me.
`sudo apt-get install gstreamer0.10-plugins-good gstreamer1.0-plugins-good`
