### ISSUE TITLE
At start if first music fail to start do not try the next automatically 

### ISSUE THREAD

**Issue by hlechner** [linuxdeepin/deepin-music#23]
I have a HDD with music files on it, however I do not mount it automatically on Linux, just if I need it. (it reduces the disk's usage and improve disk's life time)

But sometimes I forget to mount it first before I start Deepin music.

When I start it, it will flag all musics (very fast), so I need to close it fast, and mount the HDD so I can play the musics. but it turns in issue:
- All files tried by Deepin will be all marked as not found
- It will change the order of next music that will be played. (It will start on different music due to not found error)

Would be nice if in case Deepin Music does try to start the first music on list and it doesn't succeed the Deepin will stop the automatically play. (waiting for user to check it)

**Comment by Iceyer** [comment]
We will consider disable auto play next file when file missing. Or add an option for user to disable it.
Now, you can disable auto play AND resume for last position  in Settings to avoid it.

**Comment by Iceyer** [comment]
Now it only checks at most five invalid songs and stop.
