### ISSUE TITLE
Core Dump with some flac files

### ISSUE THREAD

**Issue by hlechner** [linuxdeepin/deepin-music#24]
Im receiving Core dump error when I try to play some flac files (not all flac files have this problem in Deepin Music)
```
Segmentation fault (core dumped)
```

The previously message (debug messages) on shell do not provide nothing relevant to the problem itself.

All other player that I have tested play it normally:
- vlc
- totem
- mplayer
- Rhythmbox
- Clementine

I can provide some of the files, but I can't let it available to public download for copyright reason.

An example:

Passenger - All the little lights: ``01 - Things That Stop You Dreaming.flac``
md5sum: ``ca52f914cd58ec18e0d7719c96bfbaf6  01 - Things That Stop You Dreaming.flac``

This music start to play and about a second it crashes and show core dump error message.

**Comment by Iceyer** [comment]
Can you send it to me@iceyer.net so I can test it.

**Comment by hlechner** [comment]
Email sent.

I have sent to you a tar.xz file with 3 files on it:
```
ca52f914cd58ec18e0d7719c96bfbaf6  01 - Things That Stop You Dreaming.flac
2ccaf846a9b618bf9c8d6b9a7889caa0  03 - Staring At the Stars.flac
036844b69f5624405c12e2c0c309986c  05 Travelling Alone.flac
```

All of them give me core dump error.

**Comment by hlechner** [comment]
When I opened this ticket I was using the version 3.0.12

Now I update it to 3.1.0 and seems that it is working properly now, no issue found, so I'm closing this issue.

Thanks guys!
