### ISSUE TITLE
crash on not found musics

### ISSUE THREAD

**Issue by MetaiR** [linuxdeepin/deepin-music#29]
my musics was on my hard and the hard wasn't mount yet. and when deepin-music started it was reading and failing one by one then it was crashed and made the whole system freezed.

**Comment by funilrys** [comment]
@felixonmars @Iceyer Please add `gst-libav` to the dependencies under Arch Linux (and others ?)

Indeed we recurcively get the following

``` bash
[Warning] [player.cpp           PlayerPrivate::initConnection::lambda 252] QMediaPlayer::ResourceError QSharedPointer(Playlist(0x7f571000a140)) QSharedPointer(0x7f57100e0400)
[Warning] [                                                         0] Error: "Ihrer Installation von GStreamer fehlt ein Plugin."
```
Which means that we're missing some plugin (s ?) and in the same occurance, we can't read the file(s)

After looking at the dependencies I saw that `ffmpeg` is  into the dependencies list so logicaly, we forgot the following.

> `gst-libav`    GStreamer Multimedia Framework ffmpeg Plugin

Cheers

**Comment by funilrys** [comment]
What I tried to say is that I searched and read over `pacaur -Ss gstreamear` and saw 
> `gst-libav`    GStreamer Multimedia Framework ffmpeg Plugin

So logically when you have `ffmpeg` in the dependencies and the debugger still told you that you're missing a "Gstreamer plugin" it's the right one :joy_cat:  after installing it no problem anymore so that's why I commented ...

**Comment by felixonmars** [comment]
ffmpeg was used for different parts of the program, so it's not logically related. You may also try to install other plugins like -bad -ugly and see if it works.

**Comment by funilrys** [comment]
@felixonmars On the second computer which is a clean installation I don't have gstreamer -bad or -ugly installed ... I think it's really time for Deepin (Organisation and contributors) to take the time to take a look at the dependencies on clean installation ...

**Comment by Iceyer** [comment]
It seems fixed, reopen it if appear again

**Comment by Iceyer** [comment]
@funilrys we add almost all dependencies for debian, but other release should deal by there maintainer.

**Comment by funilrys** [comment]
@Iceyer Thanks for the feedback but I stopped to actively use Deepin because it's started to become unstable under Arch on my computers.
