### ISSUE TITLE
播放问题

### ISSUE THREAD

**Issue by gaochao001** [linuxdeepin/deepin-music#3]
++++删除或清空正在播放的音乐列表，音乐依然播放，没有任何影响。
++++本地音乐、音乐电台、网络广播都会出现这种情况。
![DeepinScreenshot20130305094902](https://f.cloud.github.com/assets/2724795/219587/356721c8-8538-11e2-95fb-24479bdbf92f.png)

**Comment by Iceyer** [comment]
2.3版本已经停止维护了，请升级到3.0以上版本。
