### ISSUE TITLE
Deepin-music won't play my files - invalid or non-existent file

### ISSUE THREAD

**Issue by skullscream** [linuxdeepin/deepin-music#32]
It just won't play my mp3 files that i got. They are mostly 320Kbps. While vlc plays them no problem. Do I need some packages installed as dependencies with this? 

Using arch deepin.

**Comment by skullscream** [comment]
Nvm i fixed it without even knowing how. I did an update to my system and it installed `iproute2-4.13.0-1` and all works now.

**Comment by Iceyer** [comment]
That may because we release 3.1.6 and fix some bugs. 
however, reopen that if it appears again.

**Comment by AnwarShah** [comment]
it's still on version 3.1.7
