### ISSUE TITLE
Support sequenced music formats like midi / mod

### ISSUE THREAD

**Issue by magynhard** [linuxdeepin/deepin-music#33]
This is a feature request for adding decoding support for several sequenced music formats: MOD/MDZ, S3M/S3Z, STM/STZ, IT/ITZ, XM/XMZ, PTM/PTZ, MTM/MTZ, 669, PSM, UMX, AM/J2B, DSM, AMF, OKT/OKTA, and MO3.

And MIDI (MID).

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
