### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by ademcal** [linuxdeepin/deepin-music#34]
Missing Features:
Podcast (icecast, gpodder, itunes ...)                           
Cloud accounts (GDrive,OneDrive,Dropbox...)                   
İnternet Radios        Spotify                 
Desktop Notifications       
Equalizer                
Smart Device Syncing (İphone, Android, İpod...)                            
Converter (Mp3,Ogg,Flac ...)                 
Audio CD, DVD ...                          
Edit Tags                      
Copy to send to  smart device, cloud account       
Fetch Album Cover

if Deepin Music developers cant add upside features, My recommendation is that either the Clementine insert or the fork.

**Comment by wayneward** [comment]
Im thinking more on the line of scrobbling.. like last.fm support !!

**Comment by Iceyer** [comment]
We will not work on this feature because deepin music it aim to a simple music playerintegrated by system.
