### ISSUE TITLE
繁体界面下无法打开文件目录

### ISSUE THREAD

**Issue by gaochao001** [linuxdeepin/deepin-music#4]
(nautilus:8483): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
Could not parse arguments: Invalid byte sequence in conversion input

++繁体环境下无法打开文件目录，无法打开属性的目录。

**Comment by Iceyer** [comment]
2.3版本已经停止维护了，请升级到3.0以上版本。
