### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/deepin-music#40]
Hello,

Few issues with Deeping Music:

- Some text in the lyrics section is not localized and still in Chinese.
- Most of the times the lyrics are out of sync, meaning that even though they are correct, they scroll too soon or too late, or sometimes don't scroll at all.
- The album covers fetched online are wrong most of the times.
- The time bar is too small in height, so I'm having a hard time clicking on it to skip to a different part of a song (most of the times I click and nothing happens).

Other than that, it's an amazing app.

**Comment by LeCharlatan** [comment]
It would be good to stop the auto-repeat too, can't disable it :D
Also, possibly add a stop button would be nice

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
