### ISSUE TITLE
gnome下托盘图标会消失的问题

### ISSUE THREAD

**Issue by lxiao95** [linuxdeepin/deepin-music#43]
如果gnome锁屏之后再解锁屏幕，deepin music的托盘图标就消失了，希望能解决一下这个问题。

**Comment by lxiao95** [comment]
@Iceyer Manjaro Linux 17.1 64bit，gnome版本为3.28.1

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
