### ISSUE TITLE
Snap版本的UI需要修改

### ISSUE THREAD

**Issue by tommyvct** [linuxdeepin/deepin-music#53]
鼠标指针、滚动条、文件选择器和菜单问题很大
![image](https://user-images.githubusercontent.com/7903172/55448965-7a2d8a80-558f-11e9-92b4-bce5c7ea72c8.png)
![image](https://user-images.githubusercontent.com/7903172/55449034-aba65600-558f-11e9-8315-1a44d29a7bdc.png)
![image](https://user-images.githubusercontent.com/7903172/55449043-b95bdb80-558f-11e9-9209-cfb913d571fb.png)

**Comment by Iceyer** [comment]
系统的对话框也是这么丑吗，这个似乎也只能用系统的吧。

**Comment by BLumia** [comment]
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1585332

这个只能 snap 那边处理 = =

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
