### ISSUE TITLE
Menu translation problems

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/deepin-music#61]
There are translation problems (french) for archlinux, fedora, etc ...
See pictures below

<a href="http://zupimages.net/viewer.php?id=19/25/90fg.png"><img src="https://zupimages.net/up/19/25/90fg.png" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/25/wgki.png"><img src="https://zupimages.net/up/19/25/wgki.png" alt="" /></a>

**Comment by BLumia** [comment]
Please consider help us translating these project by [join the community translation team on Transifex](https://www.transifex.com/linuxdeepin/public/) :)

**Comment by roxfr** [comment]
Hello,
I am already registered to transifex on the deepin linux project.
I do not understand why the translation does not work on Archlinux ?

<a href="http://zupimages.net/viewer.php?id=19/26/edwj.png"><img src="https://zupimages.net/up/19/26/edwj.png" alt="" /></a>

**Comment by BLumia** [comment]
https://github.com/linuxdeepin/deepin-music/pull/62

**Comment by BLumia** [comment]
Thanks for the info, translation files now updated, should be resolved in the next update :)
