### ISSUE TITLE
Problem of translation in the menus

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/deepin-music#74]
Hi,
There are translation problems in the menus.
See photos attached.
Cordially.

**PS : The software has been fully translated into French**

<a href="http://zupimages.net/viewer.php?id=19/42/fw4j.png"><img src="https://zupimages.net/up/19/42/fw4j.png" alt="" /></a>

<a href="http://zupimages.net/viewer.php?id=19/42/y0yk.png"><img src="https://zupimages.net/up/19/42/y0yk.png" alt="" /></a>

**Comment by BLumia** [comment]
Hi and which distro and what version of deepin-music are you using?

cc @zhuxiujuancindy

**Comment by zhuxiujuancindy** [comment]
> Hi and which distro and what version of deepin-music are you using?
> 
> cc @zhuxiujuancindy

translated 6 month ago

**Comment by BLumia** [comment]
> > Hi and which distro and what version of deepin-music are you using?
> > cc @zhuxiujuancindy
> 
> translated 6 month ago

Could you please let the current deepin-music maintainer know this issue so they can look into this issue? Thanks!

**Comment by zhuxiujuancindy** [comment]
I will try to fix this in next release @roxfr

**Comment by roxfr** [comment]
I use the latest official version of Deepin (15.11)

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
