### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by tjw0lf** [linuxdeepin/deepin-music#75]
How to build this from source?

**Comment by BLumia** [comment]
Just normal `qmake` build process. get [all build detps](https://github.com/linuxdeepin/deepin-music/blob/master/debian/control#L5) installed, and then go to the source dir, to the following steps.

```
$ cd /path/to/the/source/
$ mkdir build && cd build
$ qmake ../
$ make
```

You can also open the project file (`.pro`) using QtCreator directly and build it from the IDE if you would like to modify it.

Feel free to let us know if you have any other issue when building from source, and don't forget to provide details like which distro you are using and etc.

**Comment by tjw0lf** [comment]
https://github.com/linuxdeepin/deepin-music/issues/77
