### ISSUE TITLE
UI issue in manjaro

### ISSUE THREAD

**Issue by nimdeveloper** [linuxdeepin/deepin-music#91]
Hi, I have installed deepin music in manjaro 20, but UI has some issues. this is how it looks like

![](https://user-images.githubusercontent.com/34796399/96366957-c4696300-1157-11eb-9121-842b81ca9ff3.png)

what is wrong with it?

**Comment by felixonmars** [comment]
It seems you are using KDE Plasma or some other DE other than DDE. DDE v20 applications do not work correctly on any other desktops for now.

**Comment by nimdeveloper** [comment]
Yes, it's kde, but it worked fine in manjaro 18.

**Comment by felixonmars** [comment]
The old versions used to work. Unfortunately the developers decided to break it since quite some time ago.

**Comment by nimdeveloper** [comment]
Ok, thanks
