### ISSUE TITLE
newly added music don't show up

### ISSUE THREAD

**Issue by moham96** [linuxdeepin/deepin-music#98]
during the first setup of the program, you choose the directory of the music library and it scans the directory for music, but if you add new music then it doesn't add the tracks to the library.

**Comment by uniontech-hj** [comment]
thanks for your comments. 
I can't find the problem as your operation, could you try the lastest version or upload a video with the problem.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
