### ISSUE TITLE
Small translation bug for "Copy Link Location"

### ISSUE THREAD

**Issue by roxfr** [linuxdeepin/deepin-music#99]
Hi,
Just to point out that "Copy Link Location" is not translated.
Regards,
Roxfr 

![image](https://user-images.githubusercontent.com/52124613/110980711-72271980-8366-11eb-8dc8-a11079aadef6.png)

**Comment by deepin-CD** [comment]
Thank you for your issues, We analyzed that "Copy Link Location" was not translated because the qm language pack of Qt was not installed.

**Comment by deepin-CD** [comment]
This issue will be temporarily closed due to no response received. Please reopen the issue if there're any new updates.
